name: "Link Check"
description: "Check that all new links compared to master respond properly"
inputs:
  rootURL:
    description: "The URL that root-relative links will have prepended to them"
  configFile:
    description: "A JSON file in the repo used to configure the link check"
  source:
    description: "The source to collect content entries from"
  dryRun:
    description: "Skip the check on links that otherwise would have one"
  reportUnusedPatterns:
    description: >-
      If true, informs about all link exclusion patterns that went unused.
      If set to "only", turns on dryRun and uses this check as the result.
  linkIncludePatternFiles:
    description: >-
      A string or JSON array of filenames to use as link inclusion files.
      Read as one micromatch pattern per line.
      If no include patterns are provided, all links are checked.
    required: false
  linkIncludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to whitelist links.
      If no include patterns are provided, all links are attempted.
    required: false
  linkExcludePatternFiles:
    description: >-
      A string or JSON array of filenames to use as link exclusion files.
      Read as one micromatch pattern per line.
    required: false
  linkExcludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to blacklist links.
      Takes priority over inclusion patterns.
    required: false

  fileIncludePatternFiles:
    description: >-
      A string or JSON array of paths to read as link inclusion files.
      Read as one micromatch pattern per line.
      If no include patterns are provided, all files will be scraped for links.
    required: false
  fileIncludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to whitelist files.
      If no include patterns are provided, all files will be scraped for links.
    required: false
  fileExcludePatternFiles:
    description: >-
      A string or JSON array of paths to read as link exclusion files.
      Read as one micromatch pattern per line.
      Takes priority over inclusion patterns.
    required: false
  fileExcludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to blacklist files.
      Takes priority over inclusion patterns.
    required: false
  output:
    description: >-
      A string or JSON array of output methods to use. "consoleLog", "exitCode",
      and "checkAction" are available. Multiple exit methods will be called in
      a predetermined order, so their order here does not matter.
      Defaults to ["consoleLog", "exitCode"].
outputs:
  output:
    description: "A JSON string with the test output to be handed to the Check Run"
  conclusion:
    description: "A GitHub Checks-compatible conclusion of the report"
runs:
  using: "node12"
  main: "index.js"
